### ISSUE TITLE
ElmahAppender and Unity

### ISSUE THREAD

**Issue by cbarnes01** [edwinf/log4net---ELMAH-Appender#10]
I'm getting the following error in log4net, when configuring log4net in the global.asax.

XmlHierarchyConfigurator: Cannot find Property [UseNullContext] to set object on [elmahappender_log4net.ELMAHAppender]

**Comment by edwinf** [comment]
What version of the nuget package and log4net?  are you using the latest? The latest version is a beta so you'll need to check pre-releases in package manager.

**Comment by cbarnes01** [comment]
Upgraded to the latest beta version and now it's working.  Thanks!
